# Generated by Django 2.2.24 on 2021-06-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagasakiben', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pronunciation',
            new_name='slug',
        ),
    ]
