# Generated by Django 2.2.24 on 2021-06-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nagasakiben', '0003_auto_20210609_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_by', models.CharField(max_length=50, verbose_name='投稿者')),
                ('word', models.CharField(max_length=50, verbose_name='単語')),
                ('pronunciation', models.SlugField(unique=True, verbose_name='アルファベット読み')),
                ('meaning', models.TextField(verbose_name='意味')),
                ('usage', models.TextField(verbose_name='用例')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='登録日')),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usage',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=28.069444444444443, verbose_name='記事内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='記事スラッグ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='記事タイトル'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_by', models.CharField(max_length=50, verbose_name='コメントした人')),
                ('feedback_content', models.TextField(verbose_name='コメント内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='コメント日時')),
                ('approved_feedback', models.BooleanField(default=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='nagasakiben.Dictionary', verbose_name='コメント')),
            ],
        ),
    ]
