# Generated by Django 2.2.24 on 2021-06-13 00:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagasakiben', '0005_auto_20210612_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='記事内容'),
        ),
    ]
