# Generated by Django 2.2.24 on 2021-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagasakiben', '0006_auto_20210613_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='approved_dictionary',
            field=models.BooleanField(default=True),
        ),
    ]
